### ISSUE TITLE
MacOS: Inverted Y axis

### ISSUE THREAD

**Issue by gruelingpine185** [oh-facts/mizu_mizu#2]
Something to keep in mind, MacOS uses different coordinate spaces for different objects. For windowing, the coordinates (0,0) corresponds the bottom left as opposed to the more familiar top left. Due to this difference, the mouse position logging in incorrect.

**Comment by oh-facts** [comment]
`window_height - mouse_pos_y` will probably change it to top left. Will need to track window size and work out the resizing delegate too.

**Comment by gruelingpine185** [comment]
Closing in favor of GLFW for MacOS backend.
